export type Stat = 'str' | 'dex' | 'int' | 'luk' | 'hp'
export type AttackType = 'Attack' | 'Magic'

export const classStats: Record<
	string,
	{ main: Stat; sub: Stat; attackType: AttackType }
> = {
	// Warriors
	Hero: { main: 'str', sub: 'dex', attackType: 'Attack' },
	Paladin: { main: 'str', sub: 'dex', attackType: 'Attack' },
	'Dark Knight': { main: 'str', sub: 'dex', attackType: 'Attack' },
	'Dawn Warrior': { main: 'str', sub: 'dex', attackType: 'Attack' },
	Mihile: { main: 'str', sub: 'dex', attackType: 'Attack' },
	Aran: { main: 'str', sub: 'dex', attackType: 'Attack' },
	Kaiser: { main: 'str', sub: 'dex', attackType: 'Attack' },
	Adele: { main: 'str', sub: 'dex', attackType: 'Attack' },
	Zero: { main: 'str', sub: 'dex', attackType: 'Attack' },
	'Sia Astelle': { main: 'str', sub: 'dex', attackType: 'Attack' },
	Khali: { main: 'str', sub: 'dex', attackType: 'Attack' },
	Lynn: { main: 'str', sub: 'dex', attackType: 'Attack' },
	Ark: { main: 'str', sub: 'dex', attackType: 'Attack' },

	// Paladins & Dark Knights share the same, so they’re listed above

	// Pirates (Str-based)
	Buccaneer: { main: 'str', sub: 'dex', attackType: 'Attack' },
	Corsair: { main: 'str', sub: 'dex', attackType: 'Attack' },
	Cannoneer: { main: 'str', sub: 'dex', attackType: 'Attack' },
	'Thunder Breaker': { main: 'str', sub: 'dex', attackType: 'Attack' },
	Mechanic: { main: 'str', sub: 'dex', attackType: 'Attack' },

	// Demon
	'Demon Slayer': { main: 'str', sub: 'dex', attackType: 'Attack' },
	'Demon Avenger': { main: 'hp', sub: 'str', attackType: 'Attack' },
	Xenon: { main: 'dex', sub: 'luk', attackType: 'Attack' },

	// Archers (Dex-based)
	Bowmaster: { main: 'dex', sub: 'luk', attackType: 'Attack' },
	Marksman: { main: 'dex', sub: 'luk', attackType: 'Attack' },
	Pathfinder: { main: 'dex', sub: 'luk', attackType: 'Attack' },
	'Wind Archer': { main: 'dex', sub: 'luk', attackType: 'Attack' },
	'Wild Hunter': { main: 'dex', sub: 'luk', attackType: 'Attack' },
	Mercedes: { main: 'dex', sub: 'luk', attackType: 'Attack' },
	Lara: { main: 'dex', sub: 'luk', attackType: 'Attack' },

	// Thieves (Luk-based)
	'Night Lord': { main: 'luk', sub: 'dex', attackType: 'Attack' },
	Shadower: { main: 'luk', sub: 'dex', attackType: 'Attack' },
	'Dual Blade': { main: 'luk', sub: 'dex', attackType: 'Attack' },
	'Night Walker': { main: 'luk', sub: 'dex', attackType: 'Attack' },
	Phantom: { main: 'luk', sub: 'dex', attackType: 'Attack' },
	Cadena: { main: 'luk', sub: 'dex', attackType: 'Attack' },
	Hoyoung: { main: 'luk', sub: 'dex', attackType: 'Attack' },
	'Mo Xuan': { main: 'luk', sub: 'dex', attackType: 'Attack' },
	Shade: { main: 'luk', sub: 'dex', attackType: 'Attack' },

	// Magicians (Int-based)
	'Fire Poison': { main: 'int', sub: 'luk', attackType: 'Magic' },
	'Ice Lightning': { main: 'int', sub: 'luk', attackType: 'Magic' },
	Bishop: { main: 'int', sub: 'luk', attackType: 'Magic' },
	'Blaze Wizard': { main: 'int', sub: 'luk', attackType: 'Magic' },
	'Battle Mage': { main: 'int', sub: 'luk', attackType: 'Magic' },
	Evan: { main: 'int', sub: 'luk', attackType: 'Magic' },
	Luminous: { main: 'int', sub: 'luk', attackType: 'Magic' },
	Illium: { main: 'int', sub: 'luk', attackType: 'Magic' },
	Kinesis: { main: 'int', sub: 'luk', attackType: 'Magic' },
	Kanna: { main: 'int', sub: 'luk', attackType: 'Magic' },

	// Mix-&-match or special cases
	Blaster: { main: 'str', sub: 'dex', attackType: 'Attack' },
	// …you get the idea for the rest
}

export const classNames = [
	'Hero',
	'Paladin',
	'Dark Knight',
	'Dawn Warrior',
	'Mihile',
	'Blaster',
	'Demon Slayer',
	'Demon Avenger',
	'Aran',
	'Kaiser',
	'Adele',
	'Zero',
	'Hayato',
	'Sia Astelle',
	'Fire Poison',
	'Ice Lightning',
	'Bishop',
	'Blaze Wizard',
	'Battle Mage',
	'Evan',
	'Luminous',
	'Illium',
	'Lara',
	'Kinesis',
	'Kanna',
	'Lynn',
	'Bowmaster',
	'Marksman',
	'Pathfinder',
	'Wind Archer',
	'Wild Hunter',
	'Mercedes',
	'Kain',
	'Night Lord',
	'Shadower',
	'Dual Blade',
	'Night Walker',
	'Xenon',
	'Phantom',
	'Cadena',
	'Khali',
	'Hoyoung',
	'Mo Xuan',
	'Buccaneer',
	'Corsair',
	'Cannoneer',
	'Thunder Breaker',
	'Mechanic',
	'Shade',
	'Angelic Buster',
	'Ark',
]

export const slotNames = [
	'ring1',
	'',
	'hat',
	'',
	'emblem',
	'ring2',
	'pendant1',
	'faceaccessory',
	'',
	'badge',
	'ring3',
	'pendant2',
	'eyeaccessory',
	'earring',
	'medal',
	'ring4',
	'weapon',
	'top',
	'shoulder',
	'secondary',
	'pocketitem',
	'belt',
	'bottom',
	'gloves',
	'cape',
	'',
	'',
	'shoes',
	'android',
	'mechanicalheart',
]

export const gearTypes = [
	'Hat',
	'Emblem',
	'Pendant',
	'Face Accessory',
	'Badge',
	'Eye Accessory',
	'Earrings',
	'Medal',
	'Weapon',
	'Top',
	'Shoulder',
	'Secondary',
	'Pocket Item',
	'Belt',
	'Bottom',
	'Gloves',
	'Cape',
	'Shoes',
	'Mechanical Heart',
	'Ring',
]

export const weaponNames = [
	'Ancient Bow',
	'Arm Cannon',
	'Bladecaster',
	'Bow',
	'Cane',
	'Celestial Light',
	'Chain',
	'Chakram',
	'Claw',
	'Crossbow',
	'Dagger',
	'Desperado',
	'Dual Bowgun',
	'Fan',
	'Gun',
	'Hand Cannon',
	'Heavy Sword',
	'Katana',
	'Knuckle',
	'Long Sword',
	'Lucent Gauntlet',
	'Martial Brace',
	'Memorial Staff',
	'One-Handed Axe',
	'One-Handed Blunt Weapon',
	'One-Handed Sword',
	'Polearm',
	'Psy-limiter',
	'Ritual Fan',
	'Secondary Weapon',
	'Shining Rod',
	'Soul Shooter',
	'Spear',
	'Staff',
	'Two-Handed Axe',
	'Two-Handed Blunt Weapon',
	'Two-Handed Sword',
	'Wand',
	'Whip Blade',
	'Whispershot',
]

export const secondaryNames = [
	'Abyssal Paths',
	'Arrow Fletchings',
	'Arrowheads',
	'Bladebinders',
	'Bow Thimbles',
	'Brace Bands',
	'Cards',
	'Charges',
	'Charms',
	'Chess Pieces',
	'Core Controllers',
	'Dagger Scabbards',
	'Demon Aegis',
	'Documents',
	'Dragon Essences',
	'Fan Tassels',
	'Far Sights',
	'Fists',
	'Fox Marbles',
	'Hex Seekers',
	'Iron Chains',
	'Jewels',
	'Kataras',
	'Kodachis',
	'Leaves',
	'Lucent Wings',
	'Magic Arrows',
	'Magic Books',
	'Magic Marbles',
	'Magnums',
	'Masses',
	'Medallions',
	'Orbs',
	'Ornaments',
	'Powder Kegs',
	'Relics',
	'Rosaries',
	'Shields',
	'Soul Rings',
	'Soul Shields',
	'Warp Forges',
	'Weapon Belts',
	'Wrist Bands',
]

export const hatNames = ['Arcane Umbra Mage Hat', 'Fafnir Mage Hat']

export const badgeNames = ['Genesis Badge', 'Crystal Ventus Badge']

export const shoeNames = ['Arcane Umbra Mage Shoes']

export const shoulderNames = ['Arcane Umbra Mage Shoulder']
export const ringNames = ['Superior Gollux Ring']

export const allGearNames = [
	...hatNames,
	...badgeNames,
	...shoeNames,
	...shoulderNames,
	...ringNames,
]
