import { allHatNames } from './gearNamesHat'

export const weaponNames = [
	'Ancient Bow',
	'Arm Cannon',
	'Bladecaster',
	'Bow',
	'Cane',
	'Celestial Light',
	'Chain',
	'Chakram',
	'Claw',
	'Crossbow',
	'Dagger',
	'Desperado',
	'Dual Bowgun',
	'Fan',
	'Gun',
	'Hand Cannon',
	'Heavy Sword',
	'Katana',
	'Knuckle',
	'Long Sword',
	'Lucent Gauntlet',
	'Martial Brace',
	'Memorial Staff',
	'One-Handed Axe',
	'One-Handed Blunt Weapon',
	'One-Handed Sword',
	'Polearm',
	'Psy-limiter',
	'Ritual Fan',
	'Secondary Weapon',
	'Shining Rod',
	'Soul Shooter',
	'Spear',
	'Staff',
	'Two-Handed Axe',
	'Two-Handed Blunt Weapon',
	'Two-Handed Sword',
	'Wand',
	'Whip Blade',
	'Whispershot',
]

export const secondaryNames = [
	'Abyssal Paths',
	'Arrow Fletchings',
	'Arrowheads',
	'Bladebinders',
	'Bow Thimbles',
	'Brace Bands',
	'Cards',
	'Charges',
	'Charms',
	'Chess Pieces',
	'Core Controllers',
	'Dagger Scabbards',
	'Demon Aegis',
	'Documents',
	'Dragon Essences',
	'Fan Tassels',
	'Far Sights',
	'Fists',
	'Fox Marbles',
	'Hex Seekers',
	'Iron Chains',
	'Jewels',
	'Kataras',
	'Kodachis',
	'Leaves',
	'Lucent Wings',
	'Magic Arrows',
	'Magic Books',
	'Magic Marbles',
	'Magnums',
	'Masses',
	'Medallions',
	'Orbs',
	'Ornaments',
	'Powder Kegs',
	'Relics',
	'Rosaries',
	'Shields',
	'Soul Rings',
	'Soul Shields',
	'Warp Forges',
	'Weapon Belts',
	'Wrist Bands',
]

export const badgeNames = ['Genesis Badge', 'Crystal Ventus Badge']

export const shoeNames = ['Arcane Umbra Mage Shoes']

export const shoulderNames = ['Arcane Umbra Mage Shoulder']
export const ringNames = ['Superior Gollux Ring']

export const allGearNames = [
	...allHatNames,
	...badgeNames,
	...shoeNames,
	...shoulderNames,
	...ringNames,
]
